import img1 from "../images/img2.jpg";
import img2 from "../images/img5.jpg";
import img3 from "../images/img6.jpg";
import img4 from "../images/img7.jpg";
import img5 from "../images/img8.jpg";

export const data = [
  {
    id: 1,
    description: "Skardu",
    img: img1,
    discription: "Skardu, a scenic valley with blue water and high mountains",
    discount: 10000,
    amount: 15000,
    phone: "0307-6735342",
    status: "Pending",
  },
  {
    id: 2,
    destinationname: "Naran",
    img: img2,
    briefdiscription:
      "Naran is a medium sized town situated in upper kaghan valley",
    discountamount: 6000,
    actualamount: 8000,
    phonenumber: "0307-6735342",
    status: "Accept",
  },
  {
    id: 3,
    destinationname: "Kalam",
    img: img3,
    briefdiscription:
      "Kalam, a cool and pleasant hill station in Hindu Kush Range",
    discountamount: 7000,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 4,
    destinationname: "Shugran",
    img: img4,
    briefdiscription: "hill station situated on a plateau in the Kaghan Valley",
    discountamount: 6000,
    actualamount: 8500,
    phonenumber: "0307-6735342",
    status: "Reject",
  },
  {
    id: 5,
    destinationname: "Hunza",
    img: img5,
    briefdiscription:
      "high peaks including Rakaposhi, Hunza Peak, BojahagurDuanasir II",
    discountamount: 7500,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 1,
    description: "Skardu",
    img: img1,
    discription: "Skardu, a scenic valley with blue water and high mountains",
    discount: 10000,
    amount: 15000,
    phone: "0307-6735342",
    status: "Pending",
  },
  {
    id: 2,
    destinationname: "Naran",
    img: img2,
    briefdiscription:
      "Naran is a medium sized town situated in upper kaghan valley",
    discountamount: 6000,
    actualamount: 8000,
    phonenumber: "0307-6735342",
    status: "Accept",
  },
  {
    id: 3,
    destinationname: "Kalam",
    img: img3,
    briefdiscription:
      "Kalam, a cool and pleasant hill station in Hindu Kush Range",
    discountamount: 7000,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 4,
    destinationname: "Shugran",
    img: img4,
    briefdiscription: "hill station situated on a plateau in the Kaghan Valley",
    discountamount: 6000,
    actualamount: 8500,
    phonenumber: "0307-6735342",
    status: "Reject",
  },
  {
    id: 5,
    destinationname: "Hunza",
    img: img5,
    briefdiscription:
      "high peaks including Rakaposhi, Hunza Peak, BojahagurDuanasir II",
    discountamount: 7500,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 1,
    description: "Skardu",
    img: img1,
    discription: "Skardu, a scenic valley with blue water and high mountains",
    discount: 10000,
    amount: 15000,
    phone: "0307-6735342",
    status: "Pending",
  },
  {
    id: 2,
    destinationname: "Naran",
    img: img2,
    briefdiscription:
      "Naran is a medium sized town situated in upper kaghan valley",
    discountamount: 6000,
    actualamount: 8000,
    phonenumber: "0307-6735342",
    status: "Accept",
  },
  {
    id: 3,
    destinationname: "Kalam",
    img: img3,
    briefdiscription:
      "Kalam, a cool and pleasant hill station in Hindu Kush Range",
    discountamount: 7000,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 4,
    destinationname: "Shugran",
    img: img4,
    briefdiscription: "hill station situated on a plateau in the Kaghan Valley",
    discountamount: 6000,
    actualamount: 8500,
    phonenumber: "0307-6735342",
    status: "Reject",
  },
  {
    id: 5,
    destinationname: "Hunza",
    img: img5,
    briefdiscription:
      "high peaks including Rakaposhi, Hunza Peak, BojahagurDuanasir II",
    discountamount: 7500,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 1,
    description: "Skardu",
    img: img1,
    discription: "Skardu, a scenic valley with blue water and high mountains",
    discount: 10000,
    amount: 15000,
    phone: "0307-6735342",
    status: "Pending",
  },
  {
    id: 2,
    destinationname: "Naran",
    img: img2,
    briefdiscription:
      "Naran is a medium sized town situated in upper kaghan valley",
    discountamount: 6000,
    actualamount: 8000,
    phonenumber: "0307-6735342",
    status: "Accept",
  },
  {
    id: 3,
    destinationname: "Kalam",
    img: img3,
    briefdiscription:
      "Kalam, a cool and pleasant hill station in Hindu Kush Range",
    discountamount: 7000,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 4,
    destinationname: "Shugran",
    img: img4,
    briefdiscription: "hill station situated on a plateau in the Kaghan Valley",
    discountamount: 6000,
    actualamount: 8500,
    phonenumber: "0307-6735342",
    status: "Reject",
  },
  {
    id: 5,
    destinationname: "Hunza",
    img: img5,
    briefdiscription:
      "high peaks including Rakaposhi, Hunza Peak, BojahagurDuanasir II",
    discountamount: 7500,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 1,
    description: "Skardu",
    img: img1,
    discription: "Skardu, a scenic valley with blue water and high mountains",
    discount: 10000,
    amount: 15000,
    phone: "0307-6735342",
    status: "Pending",
  },
  {
    id: 2,
    destinationname: "Naran",
    img: img2,
    briefdiscription:
      "Naran is a medium sized town situated in upper kaghan valley",
    discountamount: 6000,
    actualamount: 8000,
    phonenumber: "0307-6735342",
    status: "Accept",
  },
  {
    id: 3,
    destinationname: "Kalam",
    img: img3,
    briefdiscription:
      "Kalam, a cool and pleasant hill station in Hindu Kush Range",
    discountamount: 7000,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
  {
    id: 4,
    destinationname: "Shugran",
    img: img4,
    briefdiscription: "hill station situated on a plateau in the Kaghan Valley",
    discountamount: 6000,
    actualamount: 8500,
    phonenumber: "0307-6735342",
    status: "Reject",
  },
  {
    id: 5,
    destinationname: "Hunza",
    img: img5,
    briefdiscription:
      "high peaks including Rakaposhi, Hunza Peak, BojahagurDuanasir II",
    discountamount: 7500,
    actualamount: 9000,
    phonenumber: "0307-6735342",
    status: "CheckIn",
  },
];

export const AddsData = [
  {
    id: 1,
    name: "Active Add",
    detail: "10",
  },
  {
    id: 2,
    name: "InActive Add",
    detail: 100,
  },
  {
    id: 3,
    name: "Booking",
    detail: 70,
  },
  {
    id: 4,
    name: "Pending Booking",
    detail: 90,
  },
];
